

name: ipam2019


channels:
  
  - pytorch # deep learning
  - https://conda.anaconda.org/rdkit # Molecule
  - conda-forge # TSP

dependencies:

  # basic
  - python=3.6
  - numpy
  - mkl
  - ipython
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx

  # deep learning
  - pytorch=0.4.1
  - torchvision

  # Molecule
  - rdkit
  - seaborn

  # TSP
  - tensorboardx

  - pip:

    # TSP
    - fastprogress 



